# Generated by Django 5.1.7 on 2026-07-20 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('mobile', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('disease', models.TextField()),
                ('ward', models.CharField(max_length=100)),
                ('bed_no', models.CharField(max_length=20)),
                ('admission_date', models.DateField(default=datetime.date.today)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Admitted', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
