# Generated by Django 5.1.7 on 2026-07-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discharge_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='whatsapp',
        ),
    ]
