# Generated by Django 5.1.7 on 2026-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaap', '0002_remove_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ward',
            field=models.CharField(max_length=100, null='0'),
        ),
    ]
