# Generated by Django 5.1.7 on 2026-07-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaap', '0003_alter_patient_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
