# Generated by Django 5.1.7 on 2026-07-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaap', '0004_remove_patient_created_at_remove_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='doctor_images/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('On Leave', 'On Leave'), ('Offline', 'Offline')], default='Available', max_length=20)),
            ],
        ),
    ]
