# Generated by Django 5.1.7 on 2026-08-15 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaap', '0006_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipno', models.CharField(max_length=50)),
                ('uhid', models.CharField(max_length=100)),
                ('bill_no', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('relation_name', models.CharField(blank=True, max_length=200)),
                ('room_bed', models.CharField(blank=True, max_length=100)),
                ('doctor', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(default='PAYMENT', max_length=50)),
                ('bill_date', models.DateField()),
                ('bill_time', models.TimeField()),
                ('admission_date', models.DateField()),
                ('admission_time', models.TimeField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_time', models.TimeField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('count', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hospitaap.hospitalbill')),
            ],
        ),
    ]
