# Generated by Django 5.1.7 on 2026-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaap', '0007_hospitalbill_billservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbill',
            name='bill_no',
            field=models.CharField(max_length=50),
        ),
    ]
