# Generated by Django 5.1.7 on 2026-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaap', '0008_alter_hospitalbill_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbill',
            name='bill_no',
            field=models.CharField(max_length=50, null=''),
        ),
        migrations.AlterField(
            model_name='hospitalbill',
            name='uhid',
            field=models.CharField(max_length=100, null=''),
        ),
    ]
