# Generated by Django 5.1.7 on 2026-08-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaap', '0009_alter_hospitalbill_bill_no_alter_hospitalbill_uhid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_code', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Hematology', 'Hematology'), ('Biochemistry', 'Biochemistry'), ('Pathology', 'Pathology'), ('Immunology', 'Immunology')], max_length=50)),
                ('sample_type', models.CharField(choices=[('Whole Blood', 'Whole Blood'), ('Serum', 'Serum'), ('Plasma', 'Plasma'), ('Urine', 'Urine'), ('Other', 'Other')], max_length=50)),
                ('normal_range', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
